const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.PlatformInfo,
		C3.Plugins.AJAX,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Pin.Acts.SetDestroy,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{background1: 0},
	{Anchor: 0},
	{Tween: 0},
	{btnSettins: 0},
	{btnShop: 0},
	{BgPLine: 0},
	{Action: 0},
	{btnPlay: 0},
	{Sine: 0},
	{FindACardLogo: 0},
	{MosoLitareLogo: 0},
	{Type: 0},
	{PLine: 0},
	{Sheet: 0},
	{ThreeCardsLogo: 0},
	{OverlaySettings: 0},
	{btnLanguage: 0},
	{btnMenu: 0},
	{LogoSettings: 0},
	{bgLiner: 0},
	{btnFullscreen: 0},
	{btnSound: 0},
	{DragDrop: 0},
	{SliderMusic: 0},
	{SliderSound: 0},
	{backgroundSettings: 0},
	{Line: 0},
	{Overlay: 0},
	{ShopLogo: 0},
	{btnLeft: 0},
	{btnRight: 0},
	{LogoCard: 0},
	{btnSelect: 0},
	{boardCoin: 0},
	{"9patch": 0},
	{overlayCard: 0},
	{Id: 0},
	{btnSelectCards: 0},
	{LogoCoin: 0},
	{btnStudy: 0},
	{Num: 0},
	{Frame: 0},
	{Animation: 0},
	{My: 0},
	{StartX: 0},
	{StartY: 0},
	{Stack: 0},
	{cards: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{btnback: 0},
	{RulesLogo: 0},
	{btnNext: 0},
	{LogoWin2: 0},
	{Sprite7: 0},
	{WinLogo: 0},
	{Mode: 0},
	{btnGetCard: 0},
	{Counter: 0},
	{Anim: 0},
	{PlaceCollect1: 0},
	{PlaceCollect2: 0},
	{PlaceCollect3: 0},
	{PlaceCollect4: 0},
	{scoreBoard: 0},
	{btnMix: 0},
	{boardTimer: 0},
	{FindLogo: 0},
	{btnAttack: 0},
	{btnEndTurn: 0},
	{LogoEnemy: 0},
	{LogoPlayer: 0},
	{PlaceCard: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{Font: 0},
	{LocalStorage: 0},
	{Card: 0},
	{FindCard: 0},
	{Shirt: 0},
	{Texts: 0},
	{PlatformInfo: 0},
	{Language: 0},
	{AJAX: 0},
	{Keyboard: 0},
	{bgs: 0},
	{Pin: 0},
	{ColCards: 0},
	{Places: 0},
	{Coins: 0},
	{shirt: 0},
	{Sound: 0},
	{Music: 0},
	{IsLoad: 0},
	{Moves: 0},
	{Timer: 0},
	{LastIndex: 0},
	{LastIndex2: 0},
	{X: 0},
	{Y: 0},
	{Score: 0},
	{PlayerHP: 0},
	{EnemyHP: 0},
	{ActionCount: 0},
	{EnemyAnimation: 0},
	{EnemyFrame: 0},
	{PlayerAnimtion: 0},
	{PlayerFrame: 0}
];

self.InstanceType = {
	background1: class extends self.ISpriteInstance {},
	btnSettins: class extends self.ISpriteInstance {},
	btnShop: class extends self.ISpriteInstance {},
	BgPLine: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	FindACardLogo: class extends self.ISpriteInstance {},
	MosoLitareLogo: class extends self.ISpriteInstance {},
	PLine: class extends self.IWorldInstance {},
	Sheet: class extends self.ISpriteInstance {},
	ThreeCardsLogo: class extends self.ISpriteInstance {},
	OverlaySettings: class extends self.ISpriteInstance {},
	btnLanguage: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	LogoSettings: class extends self.ISpriteInstance {},
	bgLiner: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	SliderMusic: class extends self.ISpriteInstance {},
	SliderSound: class extends self.ISpriteInstance {},
	backgroundSettings: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Overlay: class extends self.ISpriteInstance {},
	ShopLogo: class extends self.ISpriteInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	LogoCard: class extends self.ISpriteInstance {},
	btnSelect: class extends self.ISpriteInstance {},
	boardCoin: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	overlayCard: class extends self.ISpriteInstance {},
	btnSelectCards: class extends self.ISpriteInstance {},
	LogoCoin: class extends self.ISpriteInstance {},
	btnStudy: class extends self.ISpriteInstance {},
	cards: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	btnback: class extends self.ISpriteInstance {},
	RulesLogo: class extends self.ISpriteInstance {},
	btnNext: class extends self.ISpriteInstance {},
	LogoWin2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	WinLogo: class extends self.ISpriteInstance {},
	btnGetCard: class extends self.ISpriteInstance {},
	PlaceCollect1: class extends self.ISpriteInstance {},
	PlaceCollect2: class extends self.ISpriteInstance {},
	PlaceCollect3: class extends self.ISpriteInstance {},
	PlaceCollect4: class extends self.ISpriteInstance {},
	scoreBoard: class extends self.ISpriteInstance {},
	btnMix: class extends self.ISpriteInstance {},
	boardTimer: class extends self.ISpriteInstance {},
	FindLogo: class extends self.ISpriteInstance {},
	btnAttack: class extends self.ISpriteInstance {},
	btnEndTurn: class extends self.ISpriteInstance {},
	LogoEnemy: class extends self.ISpriteInstance {},
	LogoPlayer: class extends self.ISpriteInstance {},
	PlaceCard: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Font: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Card: class extends self.IArrayInstance {},
	FindCard: class extends self.IArrayInstance {},
	Shirt: class extends self.IArrayInstance {},
	Texts: class extends self.ITextInstance {},
	PlatformInfo: class extends self.IInstance {},
	Language: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	bgs: class extends self.ISpriteInstance {},
	ColCards: class extends self.ISpriteInstance {},
	Places: class extends self.ISpriteInstance {}
}